name: Build & Push Production Image

env:
  COMMIT_SHA: ${{ github.sha }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to 5xcampus Registry
        uses: docker/login-action@v2
        with:
          registry: raw-data.5xcampus.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.release
          push: true
          cache-from: type=registry,ref=raw-data.5xcampus.com/base:cache
          cache-to: type=registry,ref=raw-data.5xcampus.com/base:cache,mode=max
          tags: raw-data.5xcampus.com/base:production
          build-args: |
            COMMIT_SHA
            RAILS_ENV=production
